<script lang="ts">import { base } from '$app/paths';
 import { places, evidence, dishById, mapsUrl, directionsUrl } from '$lib/data';
 import { progress, toggleProgress } from '$lib/progress';
 let city = 'All'; let query = ''; let onlyOriginal = false; let dish = 'All'; let onlyUntasted = false; let onlyFavorites = false; let nearby = false; let locationStatus = ''; let position: {latitude:number; longitude:number} | null = null;
 const knownDishIds = [...new Set(evidence.filter(e => e.evidenceStatus !== 'unverified').map(e => e.foodId))].sort((a,b) => (dishById.get(a)?.italianName || a).localeCompare(dishById.get(b)?.italianName || b));
 function findMe() { if (!navigator.geolocation) { locationStatus = 'Location is unavailable on this device.'; return; } locationStatus = 'Finding your location…'; navigator.geolocation.getCurrentPosition(({coords}) => { position = {latitude: coords.latitude, longitude: coords.longitude}; nearby = true; locationStatus = 'Showing distances for researched coordinates only.'; }, () => { locationStatus = 'Location permission denied or unavailable.'; }, {enableHighAccuracy:false,timeout:12000,maximumAge:120000}); }
 function distanceKm(p: {latitude?:number;longitude?:number}) { if (!position || typeof p.latitude !== 'number' || typeof p.longitude !== 'number') return null; const rad=Math.PI/180; const a=Math.sin((p.latitude-position.latitude)*rad/2)**2+Math.cos(position.latitude*rad)*Math.cos(p.latitude*rad)*Math.sin((p.longitude-position.longitude)*rad/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); }

 $: shown = places.filter((p) => (city === 'All' || p.city === city) && (!onlyOriginal || p.origin === 'original') && (!onlyFavorites || $progress.favorites.includes(p.id)) && (dish === 'All' || evidence.some(e => e.placeId === p.id && e.foodId === dish && e.evidenceStatus !== 'unverified')) && (!onlyUntasted || evidence.some(e => e.placeId === p.id && e.evidenceStatus !== 'unverified' && !$progress.tasted.includes(e.foodId))) && [p.name || '',p.address,...evidence.filter(e => e.placeId === p.id && e.evidenceStatus !== 'unverified').map(e => e.menuName || '')].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b) => nearby ? (distanceKm(a) ?? Infinity)-(distanceKm(b) ?? Infinity) : 0);
</script>
<section class="hero"><p class="eyebrow">FLORENCE · LUCCA · PISA</p><h1>Find the food worth walking for.</h1><p>Original saved stops, traditional dishes and researched menus — with Italian names you can recognize when ordering.</p></section>
<div class="controls"><label>Search places<input bind:value={query} placeholder="Restaurant, street or bakery" /></label><label>City<select bind:value={city}><option>All</option><option>Florence</option><option>Lucca</option><option>Pisa</option></select></label><label>Food to try<select bind:value={dish}><option value="All">All dishes</option>{#each knownDishIds as id}<option value={id}>{dishById.get(id)?.italianName || id}</option>{/each}</select></label><label class="check"><input type="checkbox" bind:checked={onlyOriginal}/> Original picks only</label><label class="check"><input type="checkbox" bind:checked={onlyFavorites}/> Saved only</label><label class="check"><input type="checkbox" bind:checked={onlyUntasted}/> Has food I haven't tried</label></div><div class="locationtools"><button onclick={findMe}>⌖ Find places near me</button>{#if nearby}<button onclick={() => {nearby = false;position = null;locationStatus = '';}}>Clear location</button>{/if}{#if locationStatus}<span role="status" class="muted">{locationStatus}</span>{/if}</div>
<p class="muted">{shown.length} places · <a href="{base}/foods">Explore the food dictionary →</a></p>
<div class="cards">{#each shown as place (place.id)}<article class="card"><div class="cardtop"><span class="tag">{place.city}</span><span class="tag secondary">{place.origin === 'original' ? 'Your pick' : 'Suggested'}</span></div><h2>{place.name ?? 'Venue to identify'}</h2><p class="muted">{place.address}</p>{#if nearby && distanceKm(place) !== null}<p class="distance">⌖ {distanceKm(place)?.toFixed(1)} km away (straight line)</p>{/if}{#if place.identityStatus === 'unidentified'}<p class="caution">Identity still needs checking</p>{/if}<div class="chips">{#each evidence.filter(e => e.placeId === place.id && e.evidenceStatus !== 'unverified').slice(0,4) as item}<a class="chip" href="{base}/foods/{item.foodId}">{item.menuName || dishById.get(item.foodId)?.italianName} <span class="evidence">{item.evidenceStatus === 'confirmed' ? '✓' : '◌'}</span></a>{/each}</div><div class="actions"><a href={directionsUrl(place.address)} target="_blank" rel="noopener noreferrer">Walk there ↗</a><a href={mapsUrl(place.address)} target="_blank" rel="noopener noreferrer">Map ↗</a><button class:active={$progress.visited.includes(place.id)} onclick={() => toggleProgress('visited', place.id)}>{$progress.visited.includes(place.id) ? '✓ Visited' : 'Mark visited'}</button><button aria-label="Toggle favorite" class:active={$progress.favorites.includes(place.id)} onclick={() => toggleProgress('favorites', place.id)}>{$progress.favorites.includes(place.id) ? '♥ Saved' : '♡ Save'}</button></div></article>{/each}</div>
<p class="legend">Location is requested only when you tap Find places near me. Distances appear only for verified coordinates; places without coordinates remain visible. ✓ Restaurant-owned or primary source · ◌ Third-party reported · Unverified dish leads are hidden from place cards.</p>
