<script lang="ts">import { base } from '$app/paths';
 import { places, evidence, dishById, mapsUrl, directionsUrl } from '$lib/data';
 import { progress, toggleProgress } from '$lib/progress';
 let city = 'All'; let query = ''; let onlyOriginal = false;
 $: shown = places.filter((p) => (city === 'All' || p.city === city) && (!onlyOriginal || p.origin === 'original') && (p.name || p.address).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
</script>
<section class="hero"><p class="eyebrow">FLORENCE · LUCCA · PISA</p><h1>Find the food worth walking for.</h1><p>Original saved stops, traditional dishes and researched menus — with Italian names you can recognize when ordering.</p></section>
<div class="controls"><label>Search places<input bind:value={query} placeholder="Restaurant, street or bakery" /></label><label>City<select bind:value={city}><option>All</option><option>Florence</option><option>Lucca</option><option>Pisa</option></select></label><label class="check"><input type="checkbox" bind:checked={onlyOriginal}/> Original picks only</label></div>
<p class="muted">{shown.length} places · <a href="{base}/foods">Explore the food dictionary →</a></p>
<div class="cards">{#each shown as place (place.id)}<article class="card"><div class="cardtop"><span class="tag">{place.city}</span><span class="tag secondary">{place.origin === 'original' ? 'Your pick' : 'Suggested'}</span></div><h2>{place.name ?? 'Venue to identify'}</h2><p class="muted">{place.address}</p>{#if place.identityStatus === 'unidentified'}<p class="caution">Identity still needs checking</p>{/if}<div class="chips">{#each evidence.filter(e => e.placeId === place.id && e.evidenceStatus !== 'unverified').slice(0,4) as item}<a class="chip" href="{base}/foods/{item.foodId}">{item.menuName || dishById.get(item.foodId)?.italianName} <span class="evidence">{item.evidenceStatus === 'confirmed' ? '✓' : '◌'}</span></a>{/each}</div><div class="actions"><a href={directionsUrl(place.address)} target="_blank" rel="noopener noreferrer">Walk there ↗</a><a href={mapsUrl(place.address)} target="_blank" rel="noopener noreferrer">Map ↗</a><button class:active={$progress.visited.includes(place.id)} onclick={() => toggleProgress('visited', place.id)}>{$progress.visited.includes(place.id) ? '✓ Visited' : 'Mark visited'}</button><button aria-label="Toggle favorite" class:active={$progress.favorites.includes(place.id)} onclick={() => toggleProgress('favorites', place.id)}>{$progress.favorites.includes(place.id) ? '♥ Saved' : '♡ Save'}</button></div></article>{/each}</div>
<p class="legend">✓ Restaurant-owned or primary source · ◌ Third-party reported · Unverified dish leads are hidden from place cards.</p>
